config/routes.rb
Rails.application.routes.draw do
  resources :institutes
  resources :students
  root   'static_pages#home'
  get    '/help', to: 'static_pages#help'
  get    '/about', to: 'static_pages#about'
  get    '/contact', to: 'contacts#new'
  get    '/signup', to: 'users#new'
  get    '/login', to: 'sessions#new'
  get    'matching_start', to: 'static_pages#matching_start'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  match '/contacts', to: 'contacts#new', via: 'get'
  resources :contacts, only: [:new, :create]
  resources :users
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def about
  end

  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
  The creators of this application are Emelie Dümpelmann and Rabea Schulze.
</p>

<p><strong>Emelie Dümpelmann</strong></p> <p><strong>Rabea Schulze</strong></p>
<div class="leftcontainer">
  <div class="centerwrapper">
      <div class="image">
        <%=image_tag("Emelie.jpg", height: 250, alt: "Emelie", src:"app/assets/images/Emelie.jpg") %>
        <%=image_tag("Rabea.jpg", height: 250, alt: "Rabea", src:"app/assets/images/Rabea.jpg") %>
      </div>
  </div>

  Emelie is 25 years old an student at the Leibniz University of Hannover.
  She has chosen the major "Operations Management and Research"
</div>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact</h1>
<p>
  Contact the Ruby on Rails Tutorial about the sample app at the
  <a href="http://www.railstutorial.org/contact">contact page</a>.
</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to the Matching App</h1>
  <h2><strong>Description:</strong></h2>
  <h3>
    This is the home page for a matching application. The intention is to allocate Bachelor
    students who are close to write their bachelor thesis to existing institutes of the underlying university.
    The application should provide an optimal solution so that the sorrow of the students is as small as possible.
  </h3>
  <%=image_tag("Matching.png", alt: "Matching", src:"app/assets/images/Matching.png") %>
  <br>
  <br>
  <br>
  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>

app/views/static_pages/matching_start.html.erb
<% provide(:title, 'Matching App') %>
    <% if logged_in? %>

    <h1>The Matching App </h1>
    <br>

    <div class="linkcontainer">
      <div class="centerwrapper">
          <div class="image">
            <%= link_to image_tag("Students.png", height: '100', alt: 'Student logo'), students_path, "data-turbolinks": "false"  %> <br>
            <%= link_to 'Go to student administration', students_path, "data-turbolinks": "false" %>
          </div> <br>

      <div class="image">
        <%= link_to image_tag("Institutes.png", height: '100', alt: 'Institut logo'), institutes_path, "data-turbolinks": "false"  %> <br>
        <%= link_to 'Go to institute administration', institutes_path, "data-turbolinks": "false" %>
      </div><br>

      <div class="image">
        <%= link_to image_tag("Gams.png", height: '100', alt: 'GAMS logo'), '#gams_path', "data-turbolinks": "false"  %> <br>
        <%= link_to 'Go to GAMS administration', '#gams_path', "data-turbolinks": "false" %>
      </div>
    </div>
  </div>

  <br> <br> <br>
    <% end %>